### ISSUE TITLE
使用 redis  cache 疑问

### ISSUE THREAD

**Issue by dryyun** [go-macaron/cache#10]
为什么使用 redis.put 的时候，需要 HSet 把 key 存进去 ？ 不是很懂，增加这个 hash 存在 cache key 有什么用，基于什么考虑 ？

**Comment by Unknwon** [comment]
其实吧。。我也觉得挺搞事情的，但是为了 [Flush](https://github.com/go-macaron/cache/blob/master/redis/redis.go#L113) 的时候精准删除。。。当然。。这必须是用户可自定义的呀：https://github.com/go-macaron/cache/blob/master/cache.go#L60 嘿嘿嘿
